### ISSUE TITLE
WunderBar stops to send data

### ISSUE THREAD

**Issue by ramogundogdu** [relayr/java-sdk#2]
I use the example project from [here](https://github.com/relayr/java-sdk-example) with the SDK version 1.1.0. During the execution of the project under Eclipse the WunderBar stops suddenly to send data. I use only the ID of the respective sensor to get the sensor data. Now I see, however, that the mechanism of querying data from sensors have changed. These are new fields like `"password"` and `"clientId".`

```
{
    "user": "sensorID",
    "password": "jCXQ6s2o_lN_",
    "clientId": "TKx093VNxSlOcXnESGGn5rg",
    "topic": "/v1/sensorID/"
}
```

In the example project, these informations are not queried. Could it be that this informations are missing in the query and the WunderBar therefore stops to send data? Why does the WunderBar stop to send data after the compiling and running of the code?

**Comment by perusio** [comment]
@ramogundogdu I replied to your question on the forum: https://forum.relayr.io/t/wunderbar-stops-to-send-data-with-java-sdk/1039

**Comment by ramogundogdu** [comment]
Thank you for the feedback. I thought also that the SDK isn't directly connected with WunderBar. The API of WunderBar is probably constantly in development. Since we can generate the credentials data of each sensor on the developer dashboard by ourself, surprisingly my WunderBar sends the data again since yesterday. I thought that these cases could have any influence on the data traffic of sensors.
