### ISSUE TITLE
Java SDK 1.2.0 currently broken

### ISSUE THREAD

**Issue by unstream** [relayr/java-sdk#3]
Hello,

using java-sdk-1.2.0.jar is currently not possible, as the model can no longer be parsed by the API. The change on Device.java fixes this; I could build a working sdk on the develop branch.

But our regular build is broken as it depends on the released SDK. When will you release a new version of the java-sdk?

Regards
Ingo Weichsel

**Comment by bernardpletikosa** [comment]
Hi Ingo!

I'm aware of the problem. There was a misunderstanding before our API roll-out yesterday. 
Code with a fix is already in develop and master branches.
Also new version (1.2.1) of Java SDK with the fix and some new features is available [here](https://oss.sonatype.org/content/repositories/releases/io/relayr/java-sdk/1.2.1/java-sdk-1.2.1.jar)

**Comment by unstream** [comment]
Thanks a lot, 1.2.1 solved the issue.
